apiVersion: v1
kind: Pod
metadata:
  name: tesla-app
  labels:
    app: tesla
spec:
  containers:
  - name: tesla-cont
    image:  mdedika1/tesla-app:15
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: teslasvc
spec:
  type: NodePort
  selector:
    app: tesla
  ports:
  - port: 80
    targetPort: 8080
