apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesla-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tesla-app
  template:
    metadata:
      name: tesla
      labels:
        app: tesla
    spec:
      containers:
      - name: teslatry
        image: mdedika1/tesla-app:10
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: teslasvc
spec:
  type: NodePort
  selector:
     app: tesla-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000
